version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8400:8000"
    volumes:
      - ./recipeApi:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

